title: Kenan Burak Aydin
description: Agriculture Engineer
site_title: 'Kenan CV'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: kenanburak44
blog_url: https://www.nagekar.com
email: kenanburak44@gmail.com
keybase_username:
twitter_username: kenan_burak
facebook_username: kenanburak

# absolute or relative
profile_picture: assets/images/pp.jpg

# Quantitative Genetics
